### ISSUE TITLE
Jumping from Waze

### ISSUE THREAD

**Issue by carlotino** [dudarev/mapjumper#30]
Please add Waze LiveMap and Waze Map Editor to the jumping options.

Main URLs:
- Waze LiveMap: https://www.waze.com/livemap
- Waze Map Editor: https://www.waze.com/editor/

Note: The URL can change depending on selected language, for example:
- Spanish Waze LiveMap: https://www.waze.com/es/livemap
- Spanish Waze Map Editor: https://www.waze.com/es/editor/

URL can receive lon, lat, zoom as parameters, for example:
- https://www.waze.com/livemap?lon=-3.70379&lat=40.41678&zoom=15
- https://www.waze.com/editor/?lon=-3.70379&lat=40.41678&zoom=3

Map's permalink can be extracted from the link icon (icon-link) href.

Steps to obtain lon, lat, zoom would be as follows:
1) Get permalink from HTML element ".WazeControlPermalink a.icon-link"
2) Get lon, lat, zoom from permalink
3) Apply zoom correction depending on target mapping service.

Thanks!

**Comment by dudarev** [comment]
@carlotino Thank you very much for leaving the feedback! Sorry it took so long to introduce the changes. Now it is possible to jump to and from Waze maps using code in `dev` branch. The milestone 0.6 is close to be finished and should be pushed to Chrome store at the end of April or beginning of May. 

Meanwhile, you may already start using fresh code from `dev` branch. There were a few more map providers added there and bugs fixed. To do it:

```
git clone git://github.com/dudarev/mapjumper
cd mapjumper
git checkout dev
```

Then in the Chrome:

Tools > Extensions > Developer mode > Load unpacked extension > Browse to the src directory and select the extension.
